---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 60906.
--- DateTime: 2020/12/2 21:10
---

-- init --

-- key, permitsPerSecond

local permitsPerSecond = tonumber(ARGV[1])

local stableIntervalMicros = 1000000 / permitsPerSecond
local maxPermits = 1.0 * permitsPerSecond
local storedPermits = permitsPerSecond

redis.call('HMSET', KEYS[1], 'stableIntervalMicros', stableIntervalMicros, 'storedPermits', storedPermits, 'maxPermits', maxPermits, 'nextFreeTicketMicros', 0)

return 1
