---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 60906.
--- DateTime: 2020/12/2 21:10
---


local rlInfo = redis.call('HMGET', KEYS[1], 'nextFreeTicketMicros', 'stableIntervalMicros', 'maxPermits', 'storedPermits')
local nextFreeTicketMicros = tonumber(rlInfo[1])
local stableIntervalMicros = tonumber(rlInfo[2])
local maxPermits = tonumber(rlInfo[3])
local storedPermits = tonumber(rlInfo[4])

local requiredPermits = tonumber(ARGV[1])
if requiredPermits == nil then
    requiredPermits = 1
end

-- resync --
redis.replicate_commands()

local time = redis.call('TIME')
local nowMicros = time[1] * 1000000 + time[2]

-- idle time -> tickets
if nowMicros > nextFreeTicketMicros then
    local newPermits = (nowMicros - nextFreeTicketMicros) / stableIntervalMicros
    storedPermits = math.min(maxPermits, storedPermits + newPermits)
    nextFreeTicketMicros = nowMicros
    --redis.call('HMSET', KEYS[1], 'storedPermits', storedPermits, 'nextFreeTicketMicros', nextFreeTicketMicros)
end
-- resync \\--

local oldNextFreeTicketMicros = nextFreeTicketMicros
local storedPermitsToSpend = math.min(requiredPermits, storedPermits);
local freshPermits = requiredPermits - storedPermitsToSpend
local waitMicros = freshPermits * stableIntervalMicros

nextFreeTicketMicros = nextFreeTicketMicros + waitMicros
storedPermits = storedPermits - storedPermitsToSpend

redis.call('HMSET', KEYS[1], 'storedPermits', storedPermits, 'nextFreeTicketMicros', nextFreeTicketMicros)

-- 客户端应用需要休眠阻塞的时长
local towait = math.max(oldNextFreeTicketMicros - nowMicros, 0)
return towait
